name             'example_app'
maintainer       ''
maintainer_email ''
license          ''
description      'Installs/Configures example_app'
long_description 'Installs/Configures example_app'
version          '0.1.0'

depends 'git', '~> 4.0.2'
depends 'supervisor', '~> 0.4.11'
depends 'nodejs', '~> 2.0.0'
depends 'nginx', '~> 2.7.4'
